apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-utd0
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0007-tenant/tkrw-pr712-0075-0007-app/devfile-sample-utd0@sha256:b7bee3c1e9acf411104d50bdc75d642ead7b41cd14d62455a0412bc81817adfa
        name: my-nodejs
        resources: {}
status: {}
